Repository wanted-preonboarding-team-m/01_SocialIntegrateFreed, pull requests merged in 2023-10, with the labels that each got.

#4 Chore/#1 프로젝트 기본 환경 구축
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/wanted/socialintegratefreed/global/config/p6spy/P6SpyFormatter.java
  src/main/java/com/wanted/socialintegratefreed/global/format/response/ApiResponse.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/static/index.html
  src/test/java/com/wanted/socialintegratefreed/config/restdocs/AbstractRestDocsTests.java
  src/test/java/com/wanted/socialintegratefreed/config/restdocs/RestDocsConfiguration.java
Labels: ⚙ Setting, 🚨Emergency

#3 feat: 유저엔티티 생성
  src/main/java/com/wanted/socialintegratefreed/domain/user/constant/UserEnable.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/dao/UserRepository.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/entity/BaseTimeEntity.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/entity/User.java
Labels: ✨ Feature

#9 Feature/#7 게시물 관련 entity 및 repository생성
  src/main/java/com/wanted/socialintegratefreed/domain/feed/constant/FeedType.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/dao/FeedRepository.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/entity/Feed.java
  src/main/java/com/wanted/socialintegratefreed/domain/hashtag/dao/HashtagRepository.java
  src/main/java/com/wanted/socialintegratefreed/domain/hashtag/entity/Hashtag.java
  src/main/java/com/wanted/socialintegratefreed/domain/tagmatching/dao/TagMatchingRepository.java
  src/main/java/com/wanted/socialintegratefreed/domain/tagmatching/entity/TagMatching.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/entity/User.java
  src/main/java/com/wanted/socialintegratefreed/global/entity/BaseTimeEntity.java
Labels: ✨ Feature

#12 docs: README.md 작성
  README.md
Labels: 📃 Docs

#13 feature: #6 유저 등록 구현
  build.gradle
  src/main/java/com/wanted/socialintegratefreed/SocialIntegrateFreedApplication.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/api/FeedController.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/application/FeedService.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/dto/request/FeedCreateRequest.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/dto/request/FeedUpdateRequest.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/dto/response/FeedDetailResponse.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/entity/Feed.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/api/UserController.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/application/UserService.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/auth/CustomUserDetailService.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/auth/UserPrincipal.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/config/JpaConfig.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/config/WebSecurityConfig.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/dao/UserRepository.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/dto/request/UserRequestAuthCodeDto.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/dto/request/UserRequestDto.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/dto/response/UserAccessTokenDto.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/dto/response/UserResponseAuthCodeDto.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/entity/User.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/jwt/JwtTokenProvider.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/utils/UserUtils.java
  src/main/java/com/wanted/socialintegratefreed/global/error/ErrorCode.java
  src/main/resources/application.yml
  src/test/java/com/wanted/socialintegratefreed/domain/feed/api/FeedControllerTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/feed/application/FeedServiceTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/feed/dao/FeedRepositoryTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/api/UserControllerTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/application/UserServiceTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/dao/UserRepositoryTest.java
Labels: ✨ Feature, 📬 API

#21 Feature/#11 게시물 crud 기능 구현
  build.gradle
  src/main/java/com/wanted/socialintegratefreed/SocialIntegrateFreedApplication.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/api/FeedController.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/application/FeedService.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/dto/request/FeedCreateRequest.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/dto/request/FeedUpdateRequest.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/dto/response/FeedDetailResponse.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/entity/Feed.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/api/UserController.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/application/UserService.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/auth/CustomUserDetailService.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/auth/UserPrincipal.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/config/JpaConfig.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/config/WebSecurityConfig.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/dao/UserRepository.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/dto/request/UserRequestAuthCodeDto.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/dto/request/UserRequestDto.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/dto/response/UserAccessTokenDto.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/dto/response/UserResponseAuthCodeDto.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/entity/User.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/jwt/JwtTokenProvider.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/utils/UserUtils.java
  src/main/java/com/wanted/socialintegratefreed/global/error/ErrorCode.java
  src/main/resources/application.yml
  src/test/java/com/wanted/socialintegratefreed/domain/feed/api/FeedControllerTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/feed/application/FeedServiceTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/feed/dao/FeedRepositoryTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/api/UserControllerTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/application/UserServiceTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/dao/UserRepositoryTest.java
Labels: ✨ Feature

#24 refactor: #23 유저등록 인증/인가 리팩토링
  src/main/java/com/wanted/socialintegratefreed/domain/user/api/UserController.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/application/UserService.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/auth/UserPrincipal.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/config/WebSecurityConfig.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/dto/request/UserSignUpRequestDto.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/jwt/CustomAccessDeniedHandler.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/jwt/JwtTokenProvider.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/api/UserControllerTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/application/UserServiceTest.java
Labels: ✨ Feature, 📬 API, 🚨Emergency

#27 Feature/#22 통계 api 구현
  build.gradle
  src/main/java/com/wanted/socialintegratefreed/domain/feed/api/FeedController.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/application/FeedService.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/constant/SearchType.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/constant/SearchValue.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/dao/FeedQueryRepository.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/dao/FeedQueryRepositoryImpl.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/dao/FeedRepository.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/dto/request/FeedSearchCond.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/dto/response/FeedSearchResponse.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/api/UserController.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/application/UserService.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/auth/UserPrincipal.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/jwt/JwtTokenProvider.java
  src/main/java/com/wanted/socialintegratefreed/global/error/ErrorCode.java
  src/test/java/com/wanted/socialintegratefreed/domain/feed/api/FeedControllerTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/feed/application/FeedServiceTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/feed/dao/FeedRepositoryTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/api/UserControllerTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/application/UserServiceTest.java
Labels: ✨ Feature, 📬 API

#28 test: #26 유저 등록 테스트
  src/main/java/com/wanted/socialintegratefreed/domain/user/api/UserController.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/config/WebSecurityConfig.java
  src/main/resources/application.yml
  src/test/java/com/wanted/socialintegratefreed/domain/feed/api/FeedControllerTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/annotation/WithDisableUser.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/annotation/WithMockCustomUser.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/annotation/WithMockCustomUserSecurityContextFactory.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/api/UserControllerTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/application/UserServiceTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/dao/UserRepositoryTest.java
Labels: ✅ Test

#30 Fix/#25 게시물 생성 수정을 위한 dto 검증 수정
  src/test/java/com/wanted/socialintegratefreed/domain/feed/api/FeedControllerTest.java
Labels: 🐞 BugFix

#32 Bugfix/#31 병합 충돌 해결 후처리
  src/main/java/com/wanted/socialintegratefreed/domain/feed/application/FeedService.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/api/UserController.java
  src/test/java/com/wanted/socialintegratefreed/domain/feed/api/FeedControllerTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/feed/application/FeedServiceTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/api/UserControllerTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/application/UserServiceTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/dao/UserRepositoryTest.java
Labels: 🐞 BugFix, 🚨Emergency

#34 Feature/#33 좋아요 및 공유 구현
  src/main/java/com/wanted/socialintegratefreed/domain/feed/api/FeedController.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/application/FeedService.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/constant/FeedType.java
  src/main/java/com/wanted/socialintegratefreed/domain/feed/entity/Feed.java
  src/test/java/com/wanted/socialintegratefreed/domain/feed/api/FeedControllerTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/feed/application/FeedServiceTest.java
Labels: ✨ Feature, 📬 API

#39 Fix/#38 feed repository test 수정
  src/main/java/com/wanted/socialintegratefreed/domain/user/dto/request/UserRequestAuthCodeDto.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/dto/request/UserSignUpRequestDto.java
  src/main/resources/application.yml
  src/test/java/com/wanted/socialintegratefreed/domain/feed/api/FeedControllerTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/feed/dao/FeedRepositoryTest.java
Labels: 🐞 BugFix, 🚨Emergency

#41 Refactor/#40 패키지 구조 조정 및 api 명세서 생성
  .gitignore
  src/docs/asciidoc/feed.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/user.adoc
  src/main/java/com/wanted/socialintegratefreed/domain/auth/application/CustomUserDetailService.java
  src/main/java/com/wanted/socialintegratefreed/domain/auth/entity/principal/UserPrincipal.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/application/UserService.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/auth/UserPrincipal.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/config/WebSecurityConfig.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/constant/UserEnable.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/entity/User.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/entity/UserEnable.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/jwt/CustomAccessDeniedHandler.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/jwt/JwtTokenProvider.java
  src/main/java/com/wanted/socialintegratefreed/domain/user/utils/UserUtils.java
  src/main/java/com/wanted/socialintegratefreed/global/config/jpa/JpaConfig.java
  src/main/java/com/wanted/socialintegratefreed/global/config/security/jwt/CustomAccessDeniedHandler.java
  src/main/java/com/wanted/socialintegratefreed/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/wanted/socialintegratefreed/global/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/wanted/socialintegratefreed/global/config/security/web/WebSecurityConfig.java
  src/main/java/com/wanted/socialintegratefreed/global/utils/user/UserCodeProvider.java
  src/main/resources/static/index.html
  src/test/java/com/wanted/socialintegratefreed/SocialIntegrateFreedApplicationTests.java
  src/test/java/com/wanted/socialintegratefreed/config/restdocs/AbstractRestDocsTests.java
  src/test/java/com/wanted/socialintegratefreed/domain/feed/api/FeedControllerTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/feed/dao/FeedRepositoryTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/annotation/WithDisableUser.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/annotation/WithMockCustomUserSecurityContextFactory.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/api/UserControllerTest.java
  src/test/java/com/wanted/socialintegratefreed/domain/user/application/UserServiceTest.java
Labels: 🔨 Refactor, 📃 Docs

#36 docs: README.me 갱신
  README.md
Labels: 📃 Docs
